@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Mar 19 11:29:09 +0300 2025
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim t02_Word_tb_func_impl -key {Post-Implementation:sim_1:Functional:t02_Word_tb} -tclbatch t02_Word_tb.tcl -view C:/Users/arify/WorkSpace/VHDL_processor/t02_word_RiscV_processor_V3_w_tb/t02_Word_tb_behav.wcfg -log simulate.log"
call xsim  t02_Word_tb_func_impl -key {Post-Implementation:sim_1:Functional:t02_Word_tb} -tclbatch t02_Word_tb.tcl -view C:/Users/arify/WorkSpace/VHDL_processor/t02_word_RiscV_processor_V3_w_tb/t02_Word_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
